modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved unless otherwise explicitly stated." # SWEM is All rights reserved and due to this mod being heavily tied to their code, this mod is also listed as All Rights reservered...
#HOWEVER -- I am open for branches and collaboration on my mod that respects SWEM's rights. Reach out to me and we can discuss your plans and ideas!

issueTrackerURL="https://github.com/FloweringTre/Tre-Tack-Shop--1.18.2/issues"

[[mods]]

modId="trelibrary"
version="${file.jarVersion}"
displayName="Tre's Tack Library"

# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display

logoFile="logo.png"
credits="The SWEM team for their base mod"
authors="kyraltre"


description='''A library mod to be used by SWEM addon mods to change how tack is rendered on the SWEM horses.

MUST INCLUDE THE USE OF THE REQUIRED TEXTUREPACK'''


# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.trelibrary]] #optional
# the modid of the dependency
modId="forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="[40,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"
[[dependencies.trelibrary]] #our parent mod
modId="swem"
mandatory=false
versionRange="[1.3.0-15,)"
ordering="AFTER"
side="BOTH"
[[dependencies.trelibrary]] #parent mod dependancies
modId = "geckolib3"
mandatory = false
versionRange = "[3.0.57,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.trelibrary]] #parent mod dependancies
modId = "playeranimator"
mandatory = false
versionRange = "[0.4.0+1.18,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.trelibrary]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
ordering="NONE"
side="BOTH"